### ISSUE TITLE
.NET Framework 4.5

### ISSUE THREAD

**Issue by divyesh1432** [hogaf/Castle.Facilities.Aspect#1]
It does not allow me to add reference in my wcf project (.net framework 4.5). Error target framework not supported.
Please could you make this compatible with framework 4.5 ?

**Comment by hogaf** [comment]
Thank you for your suggestion. Unnecessary dependencies removed and it is now compatible with .Net Framework 4.5 and .Net Standard 2.0.

**Comment by divyesh1432** [comment]
Thank you for adding this support...
